version: '3.8'

services:
  app:
    image: oryzons/azur:latest
    restart: unless-stopped
    container_name: azur-app
    ports:
      - '3001:3001'
    networks:
      - postgresql-engb_default
    environment:
      NODE_ENV: production
      API_PORT: 3001
      DATABASE_URL: postgresql://admin_app:mat29pau08@postgresql:5432/azur
      ADMIN_URL: http://187.127.232.142:3001
      PUBLIC_APP_URL: http://187.127.232.142:3001
      RESEND_API_KEY: re_UpiSAMgV_NN3f1PEvwkNWLj7k63yHWZ8L
      RESEND_FROM_EMAIL: onboarding@resend.dev
      RESEND_FROM_NAME: Bleu Calanque
     
networks:
  postgresql-engb_default:
    external: true
    name: postgresql-engb_default