-- AlterTable
ALTER TABLE "Partner" ADD COLUMN "linkedOffering" TEXT NOT NULL DEFAULT 'BOAT_LICENSE';
ALTER TABLE "Partner" ADD COLUMN "description" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Partner" ADD COLUMN "logoUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Partner" ADD COLUMN "price" TEXT NOT NULL DEFAULT '';
